### ISSUE TITLE
Don't have access to the creator wallet.

### ISSUE THREAD

**Issue by mkanasani** [mokshyaprotocol/aptos-token-staking#1]
Hello,  We launched our NFT project 'MetaMercs - MetaCreed Collection' back in November. The Smart contract (Candy machine) we utilized for the project had been configured with our wallet as Royalty payee but a different wallet as Creator. We don't have access to that.

Could you please provide functionality to let us manually set the creator address? Thank you

**Comment by newton-raphson** [comment]
I have pushed a solution for you in the creator branch which requires the creator to deploy the contract first and the deployer can only be the staking creator or staking admin
